deps.minecraft=26.1-snapshot-9
deps.fabric_api=0.143.5+26.1

mod.mc_dep_fabric=>1.21.11

deps.modmenu=18.0.0-alpha.5
deps.rrv = 6.4.2+26.1-snapshot-9
deps.jei = 27.4.0.15

deps.create = 26.1-snapshot-9-6.0.9-1

deps.fd = 26.1-3.4.5
deps.fabric_asm = v2.3
deps.create_deco = 2.1.2
deps.yacl = 3.8.2+26.1.0
